name: Deploy to WordPress.org
on: [push]
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: |
        npm install
        npm run build
    - name: WordPress Plugin Deploy
      uses: dinhtungdu/action-wordpress-plugin-deploy@test
